### ISSUE TITLE
Need to figure out new FFmpeg commands for breaking FFV1 files that works on new OS's

### ISSUE THREAD

**Issue by iamdamosuzuki** [iamdamosuzuki/AV-Pres-Validation-Workflows#4]
it appears that some of the evaluation commands don't work on later versions of ffmpeg or possibly on newer macOS versions. It's unclear what the problem is. It might simply be easier to include sample broken files.

**Comment by willowgerms** [comment]
This is the error I got when trying to break ffv1 files. It looks like from the message my version of ffmpeg is 4.4?

> <img width="569" alt="Screen Shot 2022-07-13 at 3 11 38 PM" src="https://user-images.githubusercontent.com/65787917/179271634-74822630-f3b0-4613-90c9-b722d8426623.png">

But when I checked this morning using the command "ffmpeg -version" it looks like I have 5.0.1. This is all new to me so any feedback is helpful!

> <img width="569" alt="Screen Shot 2022-07-15 at 9 59 11 AM" src="https://user-images.githubusercontent.com/65787917/179272303-e49d1fc3-d2a5-4408-b53e-2aed9ba67976.png">

**Comment by iamdamosuzuki** [comment]
Thanks for this willow! Is there a chance you can copy/paste the ffmpeg output and error message into the ticket? I'm having trouble recreating this problem!

**Comment by willowgerms** [comment]
Hi Morgan! I finally got around to testing this out again and guess what! It works now! So I have failed to give you an example but glad it's working on my end now :)

**Comment by iamdamosuzuki** [comment]
That's good to know! I'll close the ticket for now. thanks!
